import { CurriculumModule, CareerPathItem, ToolkitItem, TransformationItem, FAQItem, GalleryImageItem } from '../types';

export const INSTITUTION_INFO = {
  name: 'Neuronest Training Institute',
  tagline: 'Transform Learning Gaps into Stepping Stones.',
  programTitle: 'Certified Remedial Educator',
  programDuration: '6-Month Course (90 Hours)',
  hoursPerWeek: '4 hrs/week',
  scheduleType: 'Weekday Schedule',
  totalUnits: '60 In-Depth Units',
  totalModules: '6 Comprehensive Modules',
  email: 'resourcesneuronest@gmail.com',
  phone: '+91 96592 28566',
  phoneDisplay: '+91 96592 28566',
  primaryStat: '1 in 5',
  statDescription: 'Today, 1 in 5 students faces learning difficulties in traditional classrooms.',
};

export const TRAINER_INFO = {
  name: 'M.G. Yaazhini',
  role: 'Program Director & Lead Trainer',
  designation: 'Special Educator & Child Counselling Psychologist',
  credentials: [
    { title: 'MA', full: 'Master of Arts' },
    { title: 'MSc', full: 'Master of Science (Psychology)' },
    { title: 'MEd', full: 'Master of Education' },
    { title: 'PGDSE', full: 'Post Graduate Diploma in Special Education' },
    { title: 'PGDC', full: 'Post Graduate Diploma in Counselling' },
    { title: 'DLP', full: 'Diploma in Learning Problems' },
    { title: 'DCP', full: 'Diploma in Child Psychology' },
  ],
  bio: 'Specialist practitioner and thought leader dedicated to clinical remedial education, early diagnostic screening, and neurodevelopmental intervention. Guiding educators across premier institutions to master individual educational planning and multi-sensory remediation.',
  quote: 'Become the educator who understands not just WHAT a child struggles with, but WHY.',
};

export const CURRICULUM_MODULES: CurriculumModule[] = [
  {
    id: 1,
    number: '01',
    title: 'Foundations of Remedial Education',
    duration: '15 Hours · 10 Units',
    summary: 'Core principles of cognitive development, developmental milestones, and positive classroom ecologies.',
    topics: [
      'Meaning and Scope of Remedial Education',
      'Understanding Developmental Milestones (0-12 Yrs)',
      'Learning Styles and Multiple Intelligences',
      'Executive Function Skills',
      'Identifying Learning Barriers',
      'Difference Between Remedial, Special Ed & Therapy',
      'Cognitive & Language Dev Stages',
      'Behavioural Learning Principles',
      'Classroom Ecology & Positive Learning Environment',
      "Teacher's Role, Mindset & Reflective Practice",
    ],
  },
  {
    id: 2,
    number: '02',
    title: 'Neurodevelopmental Disorders (India)',
    duration: '15 Hours · 10 Units',
    summary: 'Deep clinical & educational taxonomy of neurodevelopmental variations and Indian school contexts.',
    topics: [
      'Overview of Neurodevelopmental Disorders',
      'ADHD (Attention-Deficit/Hyperactivity Disorder)',
      'Intellectual Disability',
      'Developmental Coordination Disorder (Dyspraxia)',
      'Emotional & Behavioral Challenges',
      'Specific Learning Disabilities (SLD)',
      'Autism Spectrum Disorder (ASD)',
      'Speech & Language Disorders',
      'Non-Verbal Learning Disorder (NVLD)',
      'Myths vs Facts About NDDs',
    ],
  },
  {
    id: 3,
    number: '03',
    title: 'Assessment & Identification',
    duration: '15 Hours · 10 Units',
    summary: 'Diagnostic observation, informal assessment tools, error analysis, and actionable IEP formulation.',
    topics: [
      'Referral Indicators & Early Red Flags',
      'Case History Taking & Parental Interviews',
      'Grade-Level Academic Screening',
      'Standardized Tests & Protocols',
      'Preparing Student Assessment Profile',
      'Screening Tools & Diagnostic Matrices',
      'Classroom Observation Techniques',
      'Informal & Curriculum-Based Assessment',
      'Error Analysis & Gap Mapping',
      'IEP (Individualized Education Plan) Preparation',
    ],
  },
  {
    id: 4,
    number: '04',
    title: 'Language & Literacy Remediation',
    duration: '15 Hours · 10 Units',
    summary: 'Phonological awareness, decoding frameworks, dyslexia interventions, and written expression mastery.',
    topics: [
      'Language Processing Hierarchy',
      'Phonics Instruction (Synthetic & Analytic)',
      'Auditory & Visual Discrimination Exercises',
      'Comprehension Strategies & Graphic Organizers',
      'Remediating Dysgraphia & Handwriting Deficits',
      'Pre-Literacy Skills & Phonemic Awareness',
      'Blending, Segmenting & Orthographic Mapping',
      'Reading Fluency, Prosody & Rate Training',
      'Vocabulary Enrichment & Morphological Awareness',
      'Written Expression, Sentence Structure & Composition',
    ],
  },
  {
    id: 5,
    number: '05',
    title: 'Math & Cognitive Skills Remediation',
    duration: '15 Hours · 10 Units',
    summary: 'Concrete-representational-abstract math remediation, dyscalculia intervention, and cognitive training.',
    topics: [
      'Math Remediation & CRA Methodologies',
      'Basic Operations & Computational Fluency',
      'Solving Word Problems & Semantic Deconstruction',
      'Accommodations vs Modifications in School Work',
      'Transition Planning & Academic Progression',
      'Number Sense Development & Subitizing',
      'Fractions, Decimals & Visuospatial Geometry',
      'Cognitive Skills Training (Memory & Attention)',
      'Parent Training & Home Carryover Frameworks',
      'Curriculum Integration with CBSE/ICSE/State Boards',
    ],
  },
  {
    id: 6,
    number: '06',
    title: 'Classroom Management & Parents',
    duration: '15 Hours · 10 Units',
    summary: 'Assistive technologies, RTI models, family partnerships, and Indian legal & ethical guidelines.',
    topics: [
      'Adaptive Technology & Assistive Learning Tools',
      'IEP and Legal Framework (RPwD Act & NEP Guidelines)',
      'Evidence Based Practice & Intervention Metrics',
      'Psycho Educational Assessment Interpretation',
      'Cultural Diversity & Multilingual Classroom Strategies',
      'Screening and RTI (Response to Intervention) Tiers',
      'Family Dynamics & Parental Guidance Systems',
      'Etiology of Specific Learning Disabilities',
      'Ethics, Confidentiality and Professional Legality',
      'Process of Hierarchy & Multidisciplinary Collaboration',
    ],
  },
];

export const INSTITUTIONAL_ADVANTAGES = [
  {
    id: 'nep2020',
    number: '01',
    title: 'Strict Alignment with NEP 2020',
    description: 'Structured explicitly around the National Education Policy mandate for early screening, inclusive classrooms, and universal foundational literacy & numeracy.',
    accent: '#2563D8',
  },
  {
    id: 'experiential',
    number: '02',
    title: 'Skill-Based & Experiential Focus',
    description: 'Bypasses sterile academic theory to provide immediate, hands-on clinical simulations, case reviews, and tangible multi-sensory remediation protocols.',
    accent: '#12A89D',
  },
  {
    id: 'inclusion',
    number: '03',
    title: 'Championing Inclusive Education',
    description: 'Equipping mainstream school environments to support diverse neurodevelopmental profiles without stigmatization or segregation.',
    accent: '#D92B7F',
  },
  {
    id: 'bridge',
    number: '04',
    title: 'Bridging Theory and Practice',
    description: 'Translates neurological insights into day-to-day lesson plan modifications, error analysis matrices, and classroom accommodation plans.',
    accent: '#E9A800',
  },
  {
    id: 'employability',
    number: '05',
    title: 'Enhancing Graduate Employability',
    description: 'Meets skyrocketing institutional demand across CBSE, ICSE, and International boards facing compulsory regulatory mandates for remedial resource tutors.',
    accent: '#2563D8',
  },
  {
    id: 'integration',
    number: '06',
    title: 'Seamless Academic Integration',
    description: 'Designed as a flexible 4 hours/week weekday schedule tailored to fit naturally alongside ongoing collegiate study or active school teaching schedules.',
    accent: '#12A89D',
  },
];

export const CORE_CAPABILITIES = [
  {
    id: 'why',
    title: 'Identify the "Why"',
    description: 'Pinpoint the exact cognitive and neurological root causes of reading, calculation, attention, or handwriting difficulties using structured screening tools.',
    highlight: 'Root-Cause Diagnostics',
  },
  {
    id: 'differentiation',
    title: 'Master Differentiation',
    description: 'Design highly adaptive, multi-sensory lessons that cater seamlessly to varied learning styles and neurodivergent learners within a single classroom.',
    highlight: 'Universal Design for Learning',
  },
  {
    id: 'ieps',
    title: 'Build Effective IEPs',
    description: 'Gain specialized mastery to draft, monitor, and adapt quantifiable, goal-oriented Individualized Education Plans in full alignment with board requirements.',
    highlight: 'Actionable Planning',
  },
];

export const MULTI_SENSORY_TOOLKIT: ToolkitItem[] = [
  {
    id: 'maths',
    name: 'Maths Tools',
    items: 'Abacus & Base-10 Blocks',
    category: 'Kinesthetic Numeracy',
    description: 'Concrete manipulatives that build place value, mental arithmetic, and visual number sense for dyscalculic learners.',
    iconName: 'Calculator',
  },
  {
    id: 'reading',
    name: 'Reading Aids',
    items: 'Advanced Phonics Cards',
    category: 'Phonological Decoding',
    description: 'Color-coded orthographic cards, vowel team sliders, and tactile letter cards for systematic phonics intervention.',
    iconName: 'BookOpen',
  },
  {
    id: 'writing',
    name: 'Writing Supports',
    items: 'Ergonomic Grip Aids',
    category: 'Dysgraphia Remediation',
    description: 'Adaptive silicone pencil grips, slant boards, and highlighted line writing guides to alleviate hand fatigue.',
    iconName: 'PenTool',
  },
  {
    id: 'creativity',
    name: 'Creativity Kits',
    items: 'Therapeutic Paint & Clay',
    category: 'Multi-Sensory Expression',
    description: 'Tactile modeling clay and textured art mediums to engage bilateral motor control and release cognitive tension.',
    iconName: 'Palette',
  },
  {
    id: 'brain',
    name: 'Brain Games',
    items: 'Complex Logic Puzzles',
    category: 'Executive Functioning',
    description: 'Pattern sequencing boards, working memory cards, and spatial reasoning sets to sharpen cognitive processing.',
    iconName: 'Puzzle',
  },
  {
    id: 'motor',
    name: 'Fine Motor Skills',
    items: 'Beads & Lacing Exercises',
    category: 'Neuromuscular Coordination',
    description: 'Precision threading strings, sorting tongs, and textured beads to strengthen pincer grasp and hand-eye coordination.',
    iconName: 'HandMetal',
  },
];

export const TRANSFORMATIONS: TransformationItem[] = [
  {
    id: 'slow-super',
    from: 'SLOW LEARNER',
    to: 'SUPER LEARNER',
    focusArea: 'Paced Multi-Sensory Scaffolding',
    description: 'Targeted visual and kinesthetic chunking unlocks processing speed and restores academic joy.',
  },
  {
    id: 'reader',
    from: 'STRUGGLING READER',
    to: 'SPEED READER',
    focusArea: 'Orton-Gillingham Decoding Framework',
    description: 'Systematic phonemic segmentation and sight word fluency turn decoding dread into fluid comprehension.',
  },
  {
    id: 'writer',
    from: 'WEAK WRITER',
    to: 'WORD FIGHTER',
    focusArea: 'Motor Planning & Graphic Organizers',
    description: 'Ergonomic grip adjustments and structured ideation ladders transform dysgraphia barriers into structured expression.',
  },
  {
    id: 'achiever',
    from: 'FORGETFUL LEARNER',
    to: 'FOCUSED ACHIEVER',
    focusArea: 'Working Memory & Executive Strategies',
    description: 'Visual schedules, cognitive mnemonics, and self-regulation prompts convert distraction into sustained focus.',
  },
];

export const CAREER_PATHWAYS: CareerPathItem[] = [
  {
    id: 'resource-teacher',
    title: 'Certified Resource Teacher',
    role: 'Remedial Tutor / Resource Specialist',
    environment: 'CBSE, ICSE, IGCSE & International Schools',
    description: 'Secure mandatory, highly respected positions in premier school boards implementing inclusive learning resource rooms.',
    highlights: [
      'Conduct grade-level screening and diagnostics',
      'Author formal IEPs and monitor term progression',
      'Collaborate with classroom subject teachers on accommodations',
      'Coordinate board examination dispensations and concessions',
    ],
  },
  {
    id: 'special-school',
    title: 'Special School Specialist',
    role: 'Remedial Educator / Learning Specialist',
    environment: 'Dedicated LD (Learning Disability) Special Schools & Clinics',
    description: 'Step directly into rewarding roles working with intensive neurodivergent profiles in dedicated development environments.',
    highlights: [
      'Provide intensive one-on-one multi-sensory remediation',
      'Manage specialized clinical diagnostic assessments',
      'Lead developmental coordination and literacy therapies',
      'Deliver parental psycho-education and support sessions',
    ],
  },
  {
    id: 'entrepreneur',
    title: 'Educational Entrepreneur',
    role: 'Private Practice Founder / Clinic Director',
    environment: 'Independent Child Development & Learning Centers',
    description: 'Gain the clinical confidence and tested business methodologies to successfully launch your own private remedial practice.',
    highlights: [
      'Set customized hourly consultation and therapy schedules',
      'Offer weekend and after-school remediation clinics',
      'Partner directly with pediatricians and child psychologists',
      'Build a sustainable, high-impact specialized community practice',
    ],
  },
];

export const EARNING_POTENTIAL = {
  headline: 'Build a Specialized Career',
  freelance: {
    range: '₹700 – ₹1,500',
    unit: 'PER HOUR',
    type: 'Freelance & Private Practice',
    description: 'Independent remedial specialists conducting customized one-on-one sessions, weekend clinics, and home interventions.',
  },
  fulltime: {
    range: '₹25,000 – ₹35,000',
    unit: 'PER MONTH',
    type: 'Full-Time School Positions',
    description: 'Permanent remedial resource educators in leading CBSE, ICSE, and international educational institutions.',
  },
  disclaimer: 'Earning ranges shown are indicative and may vary based on role, experience, location, institution, and market conditions.',
};

export const TARGET_AUDIENCE = [
  {
    id: 'aspiring',
    title: 'Aspiring Remedial Educators',
    description: 'Individuals wanting a specialized, high-demand career path in child development and cognitive learning.',
  },
  {
    id: 'teachers',
    title: 'School Teachers',
    description: 'Mainstream educators seeking practical tools to manage mixed-ability classrooms and diverse learners.',
  },
  {
    id: 'special-eds',
    title: 'Special Educators',
    description: 'Practitioners looking to deepen structured remedial reading, writing, and math remediation methodologies.',
  },
  {
    id: 'counsellors',
    title: 'School & Child Counsellors',
    description: 'Mental health professionals bridging emotional challenges with root academic difficulties.',
  },
  {
    id: 'professionals',
    title: 'Education Professionals',
    description: 'Curriculum planners, school heads, and administrators building inclusive institutional frameworks.',
  },
  {
    id: 'parents',
    title: 'Parents Seeking Understanding',
    description: 'Caregivers seeking evidence-backed techniques to support their own neurodivergent children at home.',
  },
  {
    id: 'graduates',
    title: 'Graduates in Psychology & B.Ed',
    description: 'Fresh graduates aiming to elevate employability with high-demand clinical classroom skills.',
  },
];

export const FAQS: FAQItem[] = [
  {
    id: 'faq-1',
    question: 'What is the Certified Remedial Educator program?',
    answer: 'The Certified Remedial Educator program is an exclusive professional training certification designed by Neuronest Training Institute. It equips educators with practical diagnostic tools, intervention strategies, classroom management skills, and multi-sensory teaching techniques to support learners facing cognitive and academic difficulties.',
  },
  {
    id: 'faq-2',
    question: 'How long is the program?',
    answer: 'The program spans 90 total hours over a comprehensive 6-month duration, structured around a flexible 4 hours/week weekday schedule.',
  },
  {
    id: 'faq-3',
    question: 'How many modules are included in the curriculum?',
    answer: 'The curriculum is organized into 6 comprehensive academic modules comprising 60 in-depth units, covering foundations, neurodevelopmental disorders, diagnostic assessment, literacy remediation, math remediation, and parent/classroom management.',
  },
  {
    id: 'faq-4',
    question: 'What will I learn in this program?',
    answer: 'You will master identifying the neurological root causes of learning difficulties, constructing Individualized Education Plans (IEPs), applying multi-sensory teaching aids (abacus, phonics cards, dysgraphia supports), and integrating inclusive accommodations under NEP 2020 guidelines.',
  },
  {
    id: 'faq-5',
    question: 'Who can join the program?',
    answer: 'The course is open to aspiring remedial educators, school teachers, special educators, child counsellors, education professionals, parents, and graduates in psychology or education looking to specialize in remedial pedagogy.',
  },
  {
    id: 'faq-6',
    question: 'Is the program suitable for working teachers?',
    answer: 'Yes. The 4 hours per week weekday schedule is intentionally engineered to fit seamlessly alongside full-time teaching duties, college degrees, or other professional commitments.',
  },
  {
    id: 'faq-7',
    question: 'What career opportunities are available after completion?',
    answer: 'Graduates can step into roles as Certified Resource Teachers in CBSE/ICSE/IGCSE board schools, remedial specialists in LD special schools, or establish independent private remedial practices.',
  },
  {
    id: 'faq-8',
    question: 'What is the weekday schedule structure?',
    answer: 'Sessions are held on weekdays totaling 4 hours per week, balanced with experiential case analysis, practical material demonstrations, and interactive unit reviews.',
  },
  {
    id: 'faq-9',
    question: 'How can I apply for the upcoming cohort?',
    answer: 'You can submit your application directly via the "Apply for the 90-Hour Program" button on this website, or connect with the Neuronest admissions team via email at resourcesneuronest@gmail.com or phone at +91 96592 28566.',
  },
  {
    id: 'faq-10',
    question: 'What certification will I receive?',
    answer: 'Upon successful completion of all 6 modules, unit evaluations, and practical submissions, candidates receive the official Certified Remedial Educator credential from Neuronest Training Institute.',
  },
];

export const GALLERY_ITEMS: GalleryImageItem[] = [
  {
    id: 'gal-1',
    title: 'One-on-One Diagnostic Remediation',
    category: 'Clinical Assessment',
    description: 'Educator guiding a student through targeted phonological and tactile decoding exercises.',
    src: '/src/assets/images/hero.jpeg',
    categoryColor: '#38BDF8',
    accentColor: '#0284C7',
    badgeBg: 'rgba(14, 165, 233, 0.22)',
    badgeBorder: 'rgba(56, 189, 248, 0.5)',
    titleColor: '#7DD3FC',
    descColor: '#E0F2FE',
  },
  {
    id: 'gal-2',
    title: 'Trainer-Led Experiential Workshop',
    category: 'Cohort Learning',
    description: 'Active case review and diagnostic scoring simulation led in the institute workshop.',
    src: '/src/assets/images/workshop.jpeg',
    categoryColor: '#818CF8',
    accentColor: '#4F46E5',
    badgeBg: 'rgba(99, 102, 241, 0.22)',
    badgeBorder: 'rgba(129, 140, 248, 0.5)',
    titleColor: '#C7D2FE',
    descColor: '#EDE9FE',
  },
  {
    id: 'gal-3',
    title: 'Multi-Sensory Remedial Toolkit in Action',
    category: 'Teaching Aids',
    description: 'Hands-on manipulation of base-10 counting blocks, phonics sliders, and tactile materials.',
    src: '/src/assets/images/multisensory.jpeg',
    categoryColor: '#FBBF24',
    accentColor: '#D97706',
    badgeBg: 'rgba(245, 158, 11, 0.22)',
    badgeBorder: 'rgba(251, 191, 36, 0.5)',
    titleColor: '#FDE68A',
    descColor: '#FEF3C7',
  },
  {
    id: 'gal-4',
    title: 'Inclusive Classroom Breakthroughs',
    category: 'Classroom Milestones',
    description: 'Celebrating individualized reading fluency milestones in an encouraging setting.',
    src: '/src/assets/images/gallery.jpeg',
    categoryColor: '#F472B6',
    accentColor: '#DB2777',
    badgeBg: 'rgba(236, 72, 153, 0.22)',
    badgeBorder: 'rgba(244, 114, 182, 0.5)',
    titleColor: '#FBCFE8',
    descColor: '#FCE7F3',
  },
  {
    id: 'gal-5',
    title: 'Program Director Mentorship',
    category: 'Expert Guidance',
    description: 'M.G. Yaazhini directing special educational intervention and child psychological strategies.',
    src: '/src/assets/images/trainer.jpeg',
    categoryColor: '#34D399',
    accentColor: '#059669',
    badgeBg: 'rgba(16, 185, 129, 0.22)',
    badgeBorder: 'rgba(52, 211, 153, 0.5)',
    titleColor: '#A7F3D0',
    descColor: '#D1FAE5',
  },
];
